package com.employee.enums;

public enum Designation {
	SOFTWARE_ENGINEER,
	ANALYST, SR_ANALYST,
	ASSOCIATE_CONSULTANT,
	CONSULTANT,
	SR_CONSULTANT,
	MANAGER,
	SR_MANAGER,
	VICE_PRESIDENT,
	PRESIDENT
}
